PROGRAM = project_01_main
DBINTERACTION = project_01_database
DISPLAY = project_01_display
GCC = gcc
GCCFLAGS = -c

all: $(PROGRAM)

$(PROGRAM):
	$(GCC) $(GCCFLAGS) $(PROGRAM).c

clean:
	rm project
